== JBoss Forge IntelliJ IDEA Plugin

Published in http://plugins.jetbrains.com/plugin/7515

Provides support for http://forge.jboss.org/[JBoss Forge] commands and wizards in IntelliJ IDEA.

=== Installation and usage

Plugin is available in IntelliJ IDEA repository under the name "JBoss Forge IDEA Plugin"
(go to `Settings > Plugins > Browse repositories...` to install).

==== JDK Version

This plugin only works with *JDK 7*. The following exception will appear if you install it and run in JDK6 :
    
    Plugin 'org.jboss.forge.plugin.idea' failed to initialize and will be disabled. Please restart IntelliJ IDEA.
    
    com.intellij.diagnostic.PluginException: org/jboss/forge/plugin/idea/service/ForgeService : Unsupported major.minor version 51.0 [Plugin: org.jboss.forge.plugin.idea]
    
IntelliJ Idea runs on JDK 6 by default. 
Make sure to change the default IDE VM use JDK7 by following instructions provided in link:https://intellij-support.jetbrains.com/entries/23455956-Selecting-the-JDK-version-the-IDE-will-run-under[here].


To show a list of commands press `Ctrl+Alt+4`.

=== Build and debug

To build the plugin, you need to have IntelliJ libraries installed in your Maven repository.
If you're Linux/Mac user, you can use `install-intellij-libs.sh` script, if that doesn't work, you can
install those JARs manually (only dependencies from POM are required).

After that, you can build the plugin with `mvn package` command (add `-DskipTests` if you don't have
Forge addons installed in your repository). The resulting ZIP file in `target/` directory can
be installed by going to `Settings > Plugins > Install plugin from disk...`.

To debug the plugin in IntelliJ IDEA, you need to install `Intellij plugin development with Maven` plugin first.
That will allow you to run a second instance of the IDE, in which you can test and debug the plugin.

After installing this plugin, you can add a plugin run/debug configuration.
To do that, go to `Run -> Edit Configurations...` and add _Plugin_ configuration.

This configuration should start a new IntelliJ window. In case the plugin is not installed, you will need
to install it manually in IDE settings and run it again.
